### PR TITLE
add sakeperp

### PR DESCRIPTION
**Pull request by beichenzhidi**

### CODE REVIEW

**Comment by masquot** [comment]
Thank you @beichenzhidi for following up on #77.

It is noted and appreciated that you started creating a dashboard given our feedback in #77. However, we can't integrate your PR into projects as is as the dashboard feels a bit rushed and seems to contain unrelated info such as Uniswap trade volume.

**Comment by beichenzhidi** [comment]
OK, please check again. I have removed uniswap

**Comment by masquot** [comment]
Thank you @beichenzhidi. You describe SakePerp as 
>  a transaction-driven decentralized perpetual contract and spot trading protocol.

From a high-quality, representative dashboard for a perpetual contract and spot trading protocol we expect more than the number of token holders and a bar chart with `event_block_number`

**Comment by masquot** [comment]
SakePerp_Dune_2021-12-03 08-19-37

**Pull request closed without merging**
