### PR TITLE
Add Candle

### PR DESCRIPTION
**Pull request by samisbakedham**
Adds Candle to the Projects List

### CODE REVIEW

**Comment by philippWassibauer** [comment]
this lacks quality of information & traction to be included for now

**Comment by samisbakedham** [comment]
> this lacks quality of information & traction to be included for now

Why? We were told that it was OK earlier

**Comment by philippWassibauer** [comment]
https://dune.com/queries/960 -> not a query on the project
cndl/Candle-Holder-Count-By-Day -> doesn't exist

**Comment by samisbakedham** [comment]
> https://dune.com/queries/960 -> not a query on the project
> 
> cndl/Candle-Holder-Count-By-Day -> doesn't exist

Fixing now...

**Pull request closed without merging**
