### PR TITLE
Updated Dashboards

### PR DESCRIPTION
**Pull request by rrodenbaugh**

### CODE REVIEW

**Comment by rrodenbaugh** [comment]
Shit 😅 I think I messed something up while trying to add some dashboards

**Comment by mewwts** [comment]
Hey @rrodenbaugh we moved to using `username/dashboard`. Can you update these?

**Comment by rrodenbaugh** [comment]
> Hey @rrodenbaugh we moved to using `username/dashboard`. Can you update these?

Okay! I believe I made the update correctly :)

**Review by mewwts — APPROVED** [review]

**Comment by mewwts** [comment]
Thanks @rrodenbaugh https://duneanalytics.com/projects/TrueFi

**Pull request merged**
