### PR TITLE
Add Candle

### PR DESCRIPTION
**Pull request by samisbakedham**
Fixed the required modifications ! :)

### CODE REVIEW

**Comment by philippWassibauer** [comment]
I don't understand. I still links to https://dune.com/queries/960, which has nothing to do with the project

**Comment by philippWassibauer** [comment]
I will close this PR down again. Next to the quality of the submission we would like to see more traction on the project to list it here.

**Comment by samisbakedham** [comment]
> I will close this PR down again. Next to the quality of the submission we would like to see more traction on the project to list it here.

We don't really want users or anything though, I suppose that is what your definition of "traction" is? We're a private chain

**Comment by philippWassibauer** [comment]
ok. what is the purpose of the charts then. we want to give insight here and I just don't see enough of that being presented here.

**Pull request closed without merging**
