### PR TITLE
Add InsurAce

### PR DESCRIPTION
**Pull request by insurace-yuxuan**

### CODE REVIEW

**Comment by masquot** [comment]
Thank you for your PR @insurace-yuxuan .

I compared the data from the dashboard https://dune.xyz/Zy/InsurAce-Cover-Statistics with the data on your website and the dashboard stats seems to be way off. 

We need the data in the dashboards to be more accurate before we can make the integration into the projects page. Feel free to submit a new PR after the necessary changes were made.

Dune has a bounty program. If you have a budget and are looking for help making dashboards, you can post your bounty in Dune's discord bounty channel.

**Comment by masquot** [comment]
Thank you your message @insurace-yuxuan. Good to know that your website includes data from multiple blockchains. Please see screenshot from https://dune.xyz/Zy/InsurAce-Cover-Statistics that shows billions and trillions of cover amounts. This is what I meant with stats that seem to be off.
InsurAceCoverStatistics

**Comment by insurace-yuxuan** [comment]
@masquot Thank you for pointing out the mistakes. We have fixed the issues in the dashboard.

**Comment by masquot** [comment]
Thank you resolving the issues @insurace-yuxuan and for adding InsurAce to Dune's project pages. Merging.

**Review by masquot — APPROVED** [review]

**Comment by masquot** [comment]
There is a small merge conflict. @insurace-yuxuan can you please add your entry to the CODEOWNERS file based on the most recent version here https://github.com/duneanalytics/projects/blob/master/CODEOWNERS and create a new commit with this change?

**Comment by insurace-yuxuan** [comment]
@masquot The merge conflict has been resolved.

**Comment by masquot** [comment]
Thank you @insurace-yuxuan. The automatic build does not pick up your page. I notice some of the keys in the `md` file are missing. I should have caught that before, sorry about that. All keys are mandatory:
> Note that all the keys are mandatory, so if you have an empty queries field it should be listed as `queries: []`.

The best way to add the new MD file with all keys is in a new pull request.

**Pull request merged**
