### PR TITLE
Add zkBob project

### PR DESCRIPTION
**Pull request by maxaleks**

### CODE REVIEW

**Review by maikReal — APPROVED** [review]

**Comment by philippWassibauer** [comment]
the embeds are done wrong, they should follow the pattern of
https://dune.com/embeds/31193/62877/a7284a40-96e1-484b-a99b-cc00c25f16b5

the rest should be ok. pls fix and I will merge

**Comment by maxaleks** [comment]
> the embeds are done wrong, they should follow the pattern of
https://dune.com/embeds/31193/62877/a7284a40-96e1-484b-a99b-cc00c25f16b5

Hi @philippWassibauer! Where I can get the last value in the url?

**Comment by philippWassibauer** [comment]
It is attached to the url when you make the query private. see example:
Screenshot 2023-06-27 at 22 13 05

**Comment by maxaleks** [comment]
> It is attached to the url when you make the query private. see example:
Thanks! I've updated the links

**Review by philippWassibauer — APPROVED** [review]

**Pull request merged**
