### PR TITLE
Revert "change logo"

### PR DESCRIPTION
**Pull request by masquot**
Reverts duneanalytics/projects#102

### CODE REVIEW

**Review by claudiaribeiro — APPROVED** [review]

**Review by va3093 — APPROVED** [review]

**Comment by newguid0** [comment]
Why was this PR created and merged?

**Comment by va3093** [comment]
@newguid0 Sorry about this. But the PR that is reverted by this PR somehow broke our internal build tool. We have not yet investigated why and how. Will undo this when we do.

**Comment by newguid0** [comment]
Ok. Should @schwoazfoara reopen the previous PR?

**Comment by va3093** [comment]
Hey @schwoazfoara and @newguid0 . We have identified the issue with your initial pull request. The image you uploaded is 1.1Mb and the max we download from GitHub is 1Mb. Please create a new PR and ensure that the image is less than 1 Mb. Thanks and sorry for the inconvenience.

**Pull request merged**
